### ISSUE TITLE
Conflicting versions of httpx and idna

### ISSUE THREAD

**Issue by taosu0216** [ZacharyZcR/SecGPT#1]
the  version of httpx is 0.13.3 and it need idna's version ==2.*    ,but the requirements.txt need idna==3.4

**Comment by ZacharyZcR** [comment]
Dear User,

Thank you for your feedback. We have noted the version compatibility issue between the current versions of httpx (0.13.3) and idna (3.4).

Please note that httpx is not a necessary component in our project. This issue may have been caused by our installation of the Google Cloud Python modules while building the translation module, for which we apologize.

In order to resolve this issue, we have revisited and tested the project dependencies, and have updated the requirements.txt file accordingly. Preliminary tests indicate that this amendment has resolved the problem.

If you encounter any other issues or difficulties while using our product, we warmly welcome your feedback. We value your input highly and will do our utmost to provide you with the best support.

Thank you once again for your understanding and cooperation!

Best regards,
ZacharyZcR

**Comment by taosu0216** [comment]
OK，thanks



---Original---
From: ***@***.***&gt;
Date: Thu, Jun 29, 2023 19:54 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [ZacharyZcR/SecGPT] Conflicting versions of httpx and idna (Issue#1)




 
Closed #1 as completed.
